from colorama import init, Fore, Back, Style
init()
def switcher ():

    text = input("Input your text \n")

    a = text
    a= a.replace('й', 'q')
    a = a.replace('Й', 'Q')
    a = a.replace('ц', 'w')
    a = a.replace('Ц', 'W')
    a = a.replace('у', 'e')
    a = a.replace('У', 'E')
    a = a.replace('к', 'r')
    a = a.replace('К', 'R')
    a = a.replace('е', 't')
    a = a.replace('Е', 'T')
    a = a.replace('н', 'y')
    a = a.replace('Н', 'Y')
    a = a.replace('г', 'u')
    a = a.replace('Г', 'U')
    a = a.replace('ш', 'i')
    a = a.replace('Ш', 'I')
    a = a.replace('щ', 'o')
    a = a.replace('Щ', 'O')
    a = a.replace('з', 'p')
    a = a.replace('З', 'P')
    a = a.replace('х', '[')
    a = a.replace('Х', '{')
    a = a.replace('ъ', ']')
    a = a.replace('Ъ', '}')
    a = a.replace('ф', 'a')
    a = a.replace('Ф', 'A')
    a = a.replace('ы', 's')
    a = a.replace('Ы', 'S')
    a = a.replace('в', 'd')
    a = a.replace('В', 'D')
    a = a.replace('а', 'f')
    a = a.replace('А', 'F')
    a = a.replace('п', 'g')
    a = a.replace('П', 'G')
    a = a.replace('р', 'h')
    a = a.replace('Р', 'H')
    a = a.replace('о', 'j')
    a = a.replace('О', 'J')
    a = a.replace('л', 'k')
    a = a.replace('Л', 'K')
    a = a.replace('д', 'l')
    a = a.replace('Д', 'L')
    a = a.replace('ж', ';')
    a = a.replace('Ж', ':')
    a = a.replace('э', "'")
    a = a.replace('Э', '"')
    a = a.replace('я', 'z')
    a = a.replace('Я', 'Z')
    a = a.replace('ч', 'x')
    a = a.replace('с', 'c')
    a = a.replace('С', 'C')
    a = a.replace('м', 'v')
    a = a.replace('М', 'V')
    a = a.replace('и', 'b')
    a = a.replace('И', 'B')
    a = a.replace('т', 'n')
    a = a.replace('Т', 'N')
    a = a.replace('ь', 'm')
    a = a.replace('Ь', 'M')
    a = a.replace(',', '?')
    a = a.replace('б', ',')
    a = a.replace('Б', '<')
    a = a.replace('ю', '.')
    a = a.replace('Ю', '>')
    a = a.replace('.', '/')

    #return (a)
    print (a)
    input("нажмите enter чтобы выйти")

switcher()


